### ISSUE TITLE
Create prover skeleton

### ISSUE THREAD

**Issue by morganthomas** [Orbis-Tertius/Orbis#27]
Create in a subfolder of this repo a project skeleton for the prover. This will be a Haskell project. The skeleton should include a Nix flake, CI with linting and testing stubbed out, and a stubbed out entry point.

**Comment by EncodePanda** [comment]
> With respect to the issue below, what is the relationship to halo2 here for provisioning it in the flake? 
> Is it Haskell-Rust FFI, CLI, other?

Let's talk about it. I need to understand first how #30 will be implemented. But still, that integration is not in the scope of this ticket.

**Comment by EncodePanda** [comment]
Ticket created in Orbis-Tertius/prover https://github.com/Orbis-Tertius/prover/issues/3
