### ISSUE TITLE
Create an example of using Halo 2 lookup arguments

### ISSUE THREAD

**Issue by morganthomas** [Orbis-Tertius/Orbis#61]
Exhibit  an implementation of 4-bit bitwise NAND using lookup tables. This would be a verification circuit which would take two 4-bit inputs and the claimed result and verify the truth of the statement.

**Comment by moreSocratic** [comment]
Two bit lookup table based XOR done.
https://github.com/zcash/halo2/pull/508
https://github.com/Orbis-Tertius/lookups-example.

**Comment by morganthomas** [comment]
Done.
