### ISSUE TITLE
Design system architecture

### ISSUE THREAD

**Issue by morganthomas** [Orbis-Tertius/Orbis#8]
Design the system architecture for the ZK rollups layer 2 solution for Cardano. This should include some recommendations about how to architect dapps built on the layer 2 solution. The deliverable is an architecture document which includes diagrams presenting different views of the architecture: specifically, at least, a system diagram (showing the components and their connections) and process diagrams (showing the steps that occur in the normal cases of system operation and key exceptional cases).

**Comment by morganthomas** [comment]
Done.

**Comment by EncodePanda** [comment]
@morganthomas is the "Orbis System Architecture" document an artifact that was created by this issue? When you said: "document which includes diagrams presenting different views of the architecture: specifically, at least, a system diagram (...) and process diagrams (...)" did you mean by that the diagrams that are present in the "Orbis System Architecture"?
