### ISSUE TITLE
Coq TinyRAM emulator setting flag on mull instruction incorrectly

### ISSUE THREAD

**Issue by marcinbugaj** [Orbis-Tertius/Orbis#90]
@AHartNtkn , FYI

```
mull r0, r3, #9121
cmov r0, #38868
answer r0
```
evaluates to 38868 on Coq TinyRAM emulator. Expected value is 0.

**Comment by AHartNtkn** [comment]
This has been fixed in the binary-integers branch.
https://github.com/Orbis-Tertius/coq-tinyram/pull/13
Also, this should have been an issue in the actual Coq TinyRAM repo.

**Comment by marcinbugaj** [comment]
I can see that binary-integers branch hasn't been merged to main yet. When can I expect it to be merged then?
